---
title: "LINEaR Dev Notebook"
output: html_document
---

```{r setup, include = FALSE}
library(devtools)
devtools::load_all()
```

```{r}
data <- data.frame(x = 1:100, y = 3 * (1:100) + rnorm(100))
fit <- clean_lm(y ~ x, data)
summary(fit$model)


plot(fit$fitted, fit$residuals, 
     main = "resid vs. fitted", 
     xlab= "fitted", ylab = "resid")
abline(h=0, lty = 2)
```

```{r}
library("ggplot2")

ggplot(fit$data, aes(x= fit$fitted, y= fit$residuals)) +
  geom_point(color = "red") +
  geom_smooth(method = "loess", se = FALSE, color = "darkred") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(title = "Residuals vs. Fitted Values", x = "Fitted Values", y = "Residuals") + 
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"))
```

```{r}
library("lmtest")
test_result <- resettest(fit$model)
test_result

if (test_result$p.value > 0.05) {
  print ("TRUE")
} else {
  "Interpret plot visually"
}
```
```{r}
data <- data.frame(x = 1:100, y = 3 * (1:100) + rnorm(100))
fit <- clean_lm(y ~ x, data)
summary(fit$model)

check_linearity(fit)
```
```{r}

res <- stats::residuals(fit$model)

plot <- ggplot2::ggplot(data.frame(res=res), ggplot2::aes(sample=res))+
    ggplot2::stat_qq(color="green") +
    ggplot2::stat_qq_line(color="darkgreen") +
    ggplot2::labs(title= "Q-Q Plot of Residuals") +
    ggplot2::theme_minimal()+
    ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5, face = "bold"))

plot
```
```{r}
clean_fit <- clean_lm(y~x, data = data)
summary(clean_fit$model)

result <- check_normality(clean_fit, use_skew_kurt = TRUE)
result$plot
result$normality_ok
result$skew_kurt

```

